### ISSUE TITLE
only one row is display in sample demp app

### ISSUE THREAD

**Issue by ghost** [muditsen/multilevelrecyclerview#1]
hi muditsen
when i test your sample app i got a app with one row recycler view 
but i think MyAdapter is not completely 
![untitled-1](https://cloud.githubusercontent.com/assets/1781462/16901470/f8bfeec0-4c59-11e6-9581-34b20f7a0323.jpg)

I dont change any thing in demo code but when i compile your sample app final work display like this

**Comment by muditsen** [comment]
If your using android support library > 23 then, use android:layout_height="wrap_content" in item_layout.xml in sample app.
